-- ============================================================
-- LINGOVA APF2 - SUPABASE / POSTGRESQL (script idempotente)
-- Ejecutar completo en Supabase > SQL Editor.
-- Sirve tanto para una base nueva como para la creada en APF1.
-- Autenticación: Supabase Auth (auth.users).
-- Roles: ESTUDIANTE, PROFESOR, ADMINISTRADOR, MARKETING, EMPRESA
-- ============================================================

-- SHA-256: se usa la función nativa sha256() de PostgreSQL (>= 11); no requiere extensiones.

-- ------------------------------------------------------------
-- 1. EMPRESAS CLIENTE
-- ------------------------------------------------------------
create table if not exists public.empresas (
  id bigint generated by default as identity primary key,
  razon_social text not null,
  ruc char(11) unique not null check (ruc ~ '^[0-9]{11}$'),
  contacto_email text,
  estado text not null default 'ACTIVA' check (estado in ('ACTIVA','INACTIVA')),
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 2. RBAC: roles, permisos y matriz rol-permiso (fuente: database/rbac_matrix.json)
-- ------------------------------------------------------------
create table if not exists public.roles (
  codigo text primary key,
  descripcion text not null
);
create table if not exists public.permisos (
  codigo text primary key,
  descripcion text not null
);
create table if not exists public.roles_permisos (
  rol text not null references public.roles(codigo) on update cascade on delete cascade,
  permiso text not null references public.permisos(codigo) on update cascade on delete cascade,
  primary key (rol, permiso)
);

insert into public.roles (codigo, descripcion) values
  ('ESTUDIANTE', 'Cursa clases, rinde evaluaciones y consulta su progreso'),
  ('PROFESOR', 'Dicta clases, programa sesiones Zoom y consulta sus pagos'),
  ('ADMINISTRADOR', 'Gestiona usuarios, cursos, pagos, tarifas y auditoría'),
  ('MARKETING', 'Planifica y mide publicaciones de Instagram'),
  ('EMPRESA', 'Empresa cliente: consulta a su personal y registra pagos de docentes')
on conflict (codigo) do update set descripcion = excluded.descripcion;

insert into public.permisos (codigo, descripcion) values
  ('usuarios:gestionar', 'Gestionar usuarios y roles'),
  ('cursos:gestionar', 'Gestionar cursos y matrículas'),
  ('pagos:listar', 'Consultar pagos (según alcance RLS)'),
  ('pagos:registrar', 'Registrar pagos y adjuntar comprobantes'),
  ('pagos:gestionar', 'Confirmar o anular pagos'),
  ('tarifas:ver', 'Consultar tarifas por hora'),
  ('tarifas:gestionar', 'Definir tarifas por hora de docentes'),
  ('zoom:ver', 'Ver clases en vivo'),
  ('zoom:programar', 'Programar y administrar clases Zoom'),
  ('auditoria:ver', 'Consultar eventos de auditoría'),
  ('auditoria:verificar', 'Verificar la cadena SHA-256 de auditoría'),
  ('marketing:gestionar', 'Gestionar publicaciones de marketing'),
  ('empresa:portal', 'Acceder al portal de empresa cliente')
on conflict (codigo) do update set descripcion = excluded.descripcion;

insert into public.roles_permisos (rol, permiso) values
  ('ESTUDIANTE', 'zoom:ver'),
  ('PROFESOR', 'pagos:listar'),
  ('PROFESOR', 'tarifas:ver'),
  ('PROFESOR', 'zoom:ver'),
  ('PROFESOR', 'zoom:programar'),
  ('ADMINISTRADOR', 'usuarios:gestionar'),
  ('ADMINISTRADOR', 'cursos:gestionar'),
  ('ADMINISTRADOR', 'pagos:listar'),
  ('ADMINISTRADOR', 'pagos:registrar'),
  ('ADMINISTRADOR', 'pagos:gestionar'),
  ('ADMINISTRADOR', 'tarifas:ver'),
  ('ADMINISTRADOR', 'tarifas:gestionar'),
  ('ADMINISTRADOR', 'zoom:ver'),
  ('ADMINISTRADOR', 'zoom:programar'),
  ('ADMINISTRADOR', 'auditoria:ver'),
  ('ADMINISTRADOR', 'auditoria:verificar'),
  ('ADMINISTRADOR', 'marketing:gestionar'),
  ('MARKETING', 'marketing:gestionar'),
  ('EMPRESA', 'empresa:portal'),
  ('EMPRESA', 'pagos:listar'),
  ('EMPRESA', 'pagos:registrar'),
  ('EMPRESA', 'tarifas:ver')
on conflict do nothing;

-- ------------------------------------------------------------
-- 2b. PERFILES (5 roles, FK a roles)
-- ------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text unique not null,
  role text not null,
  status text not null default 'ACTIVO' check (status in ('ACTIVO','INACTIVO')),
  phone text,
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists empresa_id bigint references public.empresas(id) on delete set null;

-- Ampliar el CHECK de roles (APF1 solo tenía 3 roles)
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles drop constraint if exists profiles_role_fkey;
alter table public.profiles add constraint profiles_role_fkey
  foreign key (role) references public.roles(codigo) on update cascade;

-- Un usuario EMPRESA debe pertenecer a una empresa
alter table public.profiles drop constraint if exists profiles_empresa_rol_check;
alter table public.profiles add constraint profiles_empresa_rol_check
  check (role <> 'EMPRESA' or empresa_id is not null) not valid;

-- ------------------------------------------------------------
-- 3. NÚCLEO ACADÉMICO (APF1)
-- ------------------------------------------------------------
create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  name text not null,
  level text,
  description text,
  teacher_id uuid references public.profiles(id) on delete set null,
  status text not null default 'ACTIVO' check (status in ('ACTIVO','INACTIVO')),
  created_at timestamptz not null default now()
);

create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  enrolled_at timestamptz not null default now(),
  progress numeric(5,2) not null default 0 check (progress between 0 and 100),
  status text not null default 'ACTIVA' check (status in ('ACTIVA','RETIRADA','FINALIZADA')),
  unique(student_id, course_id)
);

create table if not exists public.class_sessions (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  title text not null,
  starts_at timestamptz not null,
  meeting_url text,
  status text not null default 'PROGRAMADA' check (status in ('PROGRAMADA','COMPLETADA','CANCELADA')),
  created_at timestamptz not null default now()
);

create table if not exists public.assessments (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  title text not null,
  due_at timestamptz,
  max_score numeric(6,2) not null default 20,
  created_at timestamptz not null default now()
);

create table if not exists public.assessment_scores (
  id bigint generated by default as identity primary key,
  assessment_id bigint not null references public.assessments(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  score numeric(6,2),
  submitted_at timestamptz,
  unique(assessment_id, student_id)
);

-- ------------------------------------------------------------
-- 4. MARKETING (soporte del rol MARKETING)
-- ------------------------------------------------------------
create table if not exists public.publicaciones_instagram (
  id bigint generated by default as identity primary key,
  titulo text not null,
  contenido text,
  programada_para timestamptz,
  estado text not null default 'BORRADOR' check (estado in ('BORRADOR','PROGRAMADA','PUBLICADA','ERROR')),
  creado_por uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 5. NUEVO: PAGOS A DOCENTES
-- ------------------------------------------------------------
create table if not exists public.pagos (
  id bigint generated by default as identity primary key,
  docente_id uuid not null references public.profiles(id) on delete restrict,
  empresa_id bigint references public.empresas(id) on delete set null,
  pagador_tipo text not null default 'ADMINISTRACION' check (pagador_tipo in ('ADMINISTRACION','EMPRESA')),
  concepto text not null check (char_length(concepto) between 3 and 200),
  periodo_inicio date,
  periodo_fin date,
  horas numeric(6,2) check (horas is null or horas > 0),
  tarifa_hora numeric(10,2) check (tarifa_hora is null or tarifa_hora > 0),
  monto numeric(10,2) not null check (monto > 0),
  moneda char(3) not null default 'PEN' check (moneda in ('PEN','USD')),
  metodo_pago text not null check (metodo_pago in ('TRANSFERENCIA','DEPOSITO','YAPE','PLIN','EFECTIVO','TARJETA')),
  estado text not null default 'PENDIENTE' check (estado in ('PENDIENTE','PAGADO','VENCIDO','ANULADO')),
  referencia_operacion text,
  fecha_pago date,
  comprobante_path text,
  comprobante_nombre text,
  registrado_por uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pagos_periodo_check check (periodo_fin is null or periodo_inicio is null or periodo_fin >= periodo_inicio),
  constraint pagos_empresa_check check (pagador_tipo <> 'EMPRESA' or empresa_id is not null),
  constraint pagos_pagado_check check (estado <> 'PAGADO' or fecha_pago is not null)
);
alter table public.pagos add column if not exists horas numeric(6,2);
alter table public.pagos add column if not exists tarifa_hora numeric(10,2);
alter table public.pagos drop constraint if exists pagos_monto_horas_check;
alter table public.pagos add constraint pagos_monto_horas_check
  check (horas is null or tarifa_hora is null or monto = round(horas * tarifa_hora, 2));
create index if not exists idx_pagos_docente on public.pagos(docente_id);
create index if not exists idx_pagos_empresa on public.pagos(empresa_id);
create index if not exists idx_pagos_estado on public.pagos(estado);

-- ------------------------------------------------------------
-- 5b. NUEVO: TARIFAS POR HORA DE DOCENTES (histórico con vigencia)
-- ------------------------------------------------------------
create table if not exists public.tarifas_docentes (
  id bigint generated by default as identity primary key,
  docente_id uuid not null references public.profiles(id) on delete cascade,
  tarifa_hora numeric(10,2) not null check (tarifa_hora > 0 and tarifa_hora <= 5000),
  moneda char(3) not null default 'PEN' check (moneda in ('PEN','USD')),
  vigente_desde date not null default current_date,
  vigente_hasta date,
  creado_por uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint tarifas_vigencia_check check (vigente_hasta is null or vigente_hasta >= vigente_desde)
);
-- Una sola tarifa vigente (abierta) por docente y moneda
create unique index if not exists uq_tarifa_vigente on public.tarifas_docentes(docente_id, moneda) where vigente_hasta is null;

-- ------------------------------------------------------------
-- 5c. NUEVO: MATRÍCULA AUTOGESTIONADA (catálogo de cursos, docentes por curso, pago simulado)
-- ------------------------------------------------------------
alter table public.courses add column if not exists precio numeric(10,2) not null default 119.50 check (precio >= 0);

create table if not exists public.cursos_docentes (
  curso_id bigint not null references public.courses(id) on delete cascade,
  docente_id uuid not null references public.profiles(id) on delete cascade,
  primary key (curso_id, docente_id)
);
insert into public.cursos_docentes (curso_id, docente_id)
select id, teacher_id from public.courses where teacher_id is not null
on conflict do nothing;

alter table public.enrollments add column if not exists docente_id uuid references public.profiles(id) on delete set null;
alter table public.enrollments add column if not exists pago_simulado_ref text;
alter table public.enrollments add column if not exists monto_pagado numeric(10,2);
alter table public.enrollments add column if not exists metodo_pago_simulado text;
alter table public.cursos_docentes enable row level security;

-- ------------------------------------------------------------
-- 6. NUEVO: CLASES EN VIVO (ZOOM)
-- ------------------------------------------------------------
create table if not exists public.clases_zoom (
  id bigint generated by default as identity primary key,
  curso_id bigint not null references public.courses(id) on delete cascade,
  docente_id uuid not null references public.profiles(id) on delete restrict,
  titulo text not null check (char_length(titulo) between 3 and 150),
  descripcion text,
  zoom_meeting_id text,
  zoom_join_url text,
  zoom_start_url text,
  fecha_inicio timestamptz not null,
  duracion_minutos integer not null default 60 check (duracion_minutos between 15 and 480),
  estado text not null default 'PROGRAMADA' check (estado in ('PROGRAMADA','EN_CURSO','FINALIZADA','CANCELADA')),
  simulado boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_clases_zoom_curso on public.clases_zoom(curso_id);
create index if not exists idx_clases_zoom_docente on public.clases_zoom(docente_id);
create index if not exists idx_clases_zoom_fecha on public.clases_zoom(fecha_inicio);

-- ------------------------------------------------------------
-- 7. NUEVO: AUDITORÍA INMUTABLE CON HASH SHA-256 (cadena de hashes)
-- ------------------------------------------------------------
create table if not exists public.eventos_auditoria (
  id bigint generated always as identity primary key,
  tipo_evento text not null,
  entidad text,
  entidad_id text,
  usuario_id uuid references public.profiles(id) on delete set null,
  rol_usuario text,
  descripcion text,
  datos jsonb not null default '{}'::jsonb,
  hash_anterior text not null,
  hash_integridad text not null,
  created_at timestamptz not null default clock_timestamp()
);
create index if not exists idx_eventos_auditoria_tipo on public.eventos_auditoria(tipo_evento);
create index if not exists idx_eventos_auditoria_fecha on public.eventos_auditoria(created_at desc);

-- ============================================================
-- FUNCIONES AUXILIARES
-- ============================================================
create or replace function public.current_user_role()
returns text language sql stable security definer set search_path = public as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.current_empresa_id()
returns bigint language sql stable security definer set search_path = public as $$
  select empresa_id from public.profiles where id = auth.uid();
$$;

revoke all on function public.current_user_role() from public;
revoke all on function public.current_empresa_id() from public;
grant execute on function public.current_user_role() to authenticated;
grant execute on function public.current_empresa_id() to authenticated;

-- Permisos del usuario autenticado
create or replace function public.tiene_permiso(p_permiso text)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.roles_permisos rp
                 where rp.rol = public.current_user_role() and rp.permiso = p_permiso);
$$;
revoke all on function public.tiene_permiso(text) from public;
grant execute on function public.tiene_permiso(text) to authenticated;

-- Definir tarifa por hora: cierra la vigente y abre la nueva (solo con permiso tarifas:gestionar)
create or replace function public.establecer_tarifa(p_docente uuid, p_tarifa numeric, p_moneda text default 'PEN', p_desde date default current_date)
returns bigint language plpgsql security definer set search_path = public as $$
declare v_id bigint;
begin
  if not public.tiene_permiso('tarifas:gestionar') then raise exception 'Sin permiso tarifas:gestionar' using errcode = '42501'; end if;
  if not exists (select 1 from public.profiles where id = p_docente and role = 'PROFESOR') then
    raise exception 'El beneficiario debe ser un docente' using errcode = '22023'; end if;
  update public.tarifas_docentes set vigente_hasta = greatest(vigente_desde, p_desde - 1)
   where docente_id = p_docente and moneda = p_moneda and vigente_hasta is null;
  insert into public.tarifas_docentes (docente_id, tarifa_hora, moneda, vigente_desde, creado_por)
  values (p_docente, p_tarifa, p_moneda, p_desde, auth.uid()) returning id into v_id;
  insert into public.eventos_auditoria (tipo_evento, entidad, entidad_id, usuario_id, descripcion, datos)
  values ('TARIFA_ESTABLECIDA', 'tarifas_docentes', v_id::text, auth.uid(), 'Nueva tarifa por hora',
          jsonb_build_object('docente_id', p_docente, 'tarifa_hora', p_tarifa, 'moneda', p_moneda, 'desde', p_desde));
  return v_id;
end $$;
revoke all on function public.establecer_tarifa(uuid,numeric,text,date) from public;
grant execute on function public.establecer_tarifa(uuid,numeric,text,date) to authenticated;

-- Hash SHA-256 de un evento (misma fórmula en trigger y en verificación)
create or replace function public.calcular_hash_evento(
  p_id bigint, p_hash_anterior text, p_tipo text, p_entidad text, p_entidad_id text,
  p_usuario uuid, p_rol text, p_descripcion text, p_datos jsonb, p_fecha timestamptz
) returns text language sql immutable set search_path = public as $$
  select encode(sha256(convert_to(concat_ws('|',
    p_id::text, p_hash_anterior, p_tipo, coalesce(p_entidad,''), coalesce(p_entidad_id,''),
    coalesce(p_usuario::text,''), coalesce(p_rol,''), coalesce(p_descripcion,''),
    p_datos::text, to_char(p_fecha at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US')
  ), 'UTF8')), 'hex');
$$;

-- Trigger BEFORE INSERT: encadena y firma cada evento (el cliente no puede falsificar hashes)
create or replace function public.trg_eventos_auditoria_hash()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_prev text;
begin
  perform pg_advisory_xact_lock(710001);               -- serializa la cadena
  select hash_integridad into v_prev from public.eventos_auditoria order by id desc limit 1;
  new.hash_anterior := coalesce(v_prev, 'GENESIS');
  new.created_at := clock_timestamp();
  if new.usuario_id is not null then
    new.rol_usuario := (select role from public.profiles where id = new.usuario_id);
  end if;
  new.hash_integridad := public.calcular_hash_evento(
    new.id, new.hash_anterior, new.tipo_evento, new.entidad, new.entidad_id,
    new.usuario_id, new.rol_usuario, new.descripcion, new.datos, new.created_at);
  return new;
end $$;

drop trigger if exists eventos_auditoria_hash on public.eventos_auditoria;
create trigger eventos_auditoria_hash before insert on public.eventos_auditoria
for each row execute function public.trg_eventos_auditoria_hash();

-- Trigger de inmutabilidad (append-only)
create or replace function public.trg_eventos_auditoria_inmutable()
returns trigger language plpgsql as $$
begin
  raise exception 'eventos_auditoria es de solo inserción: % no permitido', tg_op using errcode = '42501';
end $$;

drop trigger if exists eventos_auditoria_no_update on public.eventos_auditoria;
create trigger eventos_auditoria_no_update before update or delete on public.eventos_auditoria
for each row execute function public.trg_eventos_auditoria_inmutable();

drop trigger if exists eventos_auditoria_no_truncate on public.eventos_auditoria;
create trigger eventos_auditoria_no_truncate before truncate on public.eventos_auditoria
for each statement execute function public.trg_eventos_auditoria_inmutable();

revoke insert, update, delete, truncate on public.eventos_auditoria from anon, authenticated;

-- Registro de eventos: única vía de escritura para usuarios autenticados
create or replace function public.registrar_evento(
  p_tipo text, p_entidad text default null, p_entidad_id text default null,
  p_descripcion text default null, p_datos jsonb default '{}'::jsonb
) returns bigint language plpgsql security definer set search_path = public as $$
declare v_id bigint;
begin
  if auth.uid() is null then raise exception 'No autenticado' using errcode = '28000'; end if;
  insert into public.eventos_auditoria (tipo_evento, entidad, entidad_id, usuario_id, descripcion, datos)
  values (p_tipo, p_entidad, p_entidad_id, auth.uid(), p_descripcion, coalesce(p_datos,'{}'::jsonb))
  returning id into v_id;
  return v_id;
end $$;
revoke all on function public.registrar_evento(text,text,text,text,jsonb) from public;
grant execute on function public.registrar_evento(text,text,text,text,jsonb) to authenticated;

-- Verificación de la cadena (solo ADMINISTRADOR): devuelve los eventos alterados
create or replace function public.verificar_cadena_auditoria()
returns table(evento_id bigint, valido boolean, motivo text)
language plpgsql security definer set search_path = public as $$
declare r record; v_prev text := 'GENESIS'; v_calc text;
begin
  if public.current_user_role() is distinct from 'ADMINISTRADOR' then
    raise exception 'Solo el administrador puede verificar la auditoría' using errcode = '42501';
  end if;
  for r in select * from public.eventos_auditoria order by id loop
    v_calc := public.calcular_hash_evento(r.id, r.hash_anterior, r.tipo_evento, r.entidad, r.entidad_id,
              r.usuario_id, r.rol_usuario, r.descripcion, r.datos, r.created_at);
    if r.hash_anterior <> v_prev then
      evento_id := r.id; valido := false; motivo := 'Cadena rota: hash_anterior no coincide'; return next;
    elsif r.hash_integridad <> v_calc then
      evento_id := r.id; valido := false; motivo := 'Contenido alterado: hash no coincide'; return next;
    end if;
    v_prev := r.hash_integridad;
  end loop;
  return;
end $$;
revoke all on function public.verificar_cadena_auditoria() from public;
grant execute on function public.verificar_cadena_auditoria() to authenticated;

-- Migración de la tabla de APF1 (audit_events) hacia la cadena firmada
do $$
begin
  if to_regclass('public.audit_events') is not null
     and not exists (select 1 from public.eventos_auditoria where tipo_evento = 'MIGRACION_APF1') then
    insert into public.eventos_auditoria (tipo_evento, entidad, entidad_id, usuario_id, descripcion, datos)
    select 'MIGRACION_APF1', 'audit_events', a.id::text, a.user_id,
           coalesce(a.event_type,'') || ': ' || coalesce(a.description,''),
           jsonb_build_object('fecha_original', a.created_at)
    from public.audit_events a order by a.id;
  end if;
end $$;

-- Trigger updated_at
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$ begin new.updated_at := now(); return new; end $$;
drop trigger if exists pagos_updated on public.pagos;
create trigger pagos_updated before update on public.pagos for each row execute function public.set_updated_at();
drop trigger if exists clases_zoom_updated on public.clases_zoom;
create trigger clases_zoom_updated before update on public.clases_zoom for each row execute function public.set_updated_at();

-- ============================================================
-- ROW LEVEL SECURITY (RBAC a nivel de base de datos)
-- ============================================================
alter table public.roles enable row level security;
alter table public.permisos enable row level security;
alter table public.roles_permisos enable row level security;
alter table public.tarifas_docentes enable row level security;
alter table public.empresas enable row level security;
alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.enrollments enable row level security;
alter table public.class_sessions enable row level security;
alter table public.assessments enable row level security;
alter table public.assessment_scores enable row level security;
alter table public.publicaciones_instagram enable row level security;
alter table public.pagos enable row level security;
alter table public.clases_zoom enable row level security;
alter table public.eventos_auditoria enable row level security;

do $$
declare p record;
begin
  for p in select schemaname, tablename, policyname from pg_policies
           where schemaname = 'public' and tablename in
           ('roles','permisos','roles_permisos','tarifas_docentes','cursos_docentes','empresas','profiles','courses','enrollments','class_sessions','assessments','assessment_scores',
            'publicaciones_instagram','pagos','clases_zoom','eventos_auditoria','audit_events')
  loop
    execute format('drop policy if exists %I on %I.%I', p.policyname, p.schemaname, p.tablename);
  end loop;
end $$;

-- roles / permisos: lectura para autenticados; escritura solo con service_role / migraciones
create policy roles_select on public.roles for select to authenticated using (true);
create policy permisos_select on public.permisos for select to authenticated using (true);
create policy roles_permisos_select on public.roles_permisos for select to authenticated using (true);
revoke insert, update, delete, truncate on public.roles, public.permisos, public.roles_permisos from anon, authenticated;

-- tarifas_docentes: ADMIN todo (vía función); docente la suya; empresa ve tarifas de docentes
create policy tarifas_select on public.tarifas_docentes for select to authenticated
using (public.current_user_role() in ('ADMINISTRADOR','EMPRESA') or docente_id = auth.uid());
revoke insert, update, delete on public.tarifas_docentes from anon, authenticated;  -- escritura solo por establecer_tarifa()

-- empresas
create policy empresas_select on public.empresas for select to authenticated
using (public.current_user_role() = 'ADMINISTRADOR' or id = public.current_empresa_id());
create policy empresas_admin_write on public.empresas for all to authenticated
using (public.current_user_role() = 'ADMINISTRADOR') with check (public.current_user_role() = 'ADMINISTRADOR');

-- profiles
create policy profiles_select on public.profiles for select to authenticated
using (
  id = auth.uid()
  or public.current_user_role() = 'ADMINISTRADOR'
  or (public.current_user_role() = 'PROFESOR' and role = 'ESTUDIANTE')
  or (public.current_user_role() = 'EMPRESA' and (role = 'PROFESOR' or empresa_id = public.current_empresa_id()))
);
create policy profiles_update on public.profiles for update to authenticated
using (id = auth.uid() or public.current_user_role() = 'ADMINISTRADOR')
with check (
  public.current_user_role() = 'ADMINISTRADOR'
  or (id = auth.uid() and role = (select p.role from public.profiles p where p.id = auth.uid()))  -- no auto-escalada de rol
);

-- courses
create policy courses_select on public.courses for select to authenticated using (true);
create policy courses_insert on public.courses for insert to authenticated with check (public.current_user_role() = 'ADMINISTRADOR');
create policy courses_update on public.courses for update to authenticated
using (public.current_user_role() = 'ADMINISTRADOR' or teacher_id = auth.uid())
with check (public.current_user_role() = 'ADMINISTRADOR' or teacher_id = auth.uid());

-- enrollments
create policy enrollments_select on public.enrollments for select to authenticated
using (student_id = auth.uid() or public.current_user_role() = 'ADMINISTRADOR'
  or docente_id = auth.uid()
  or (docente_id is null and exists (select 1 from public.courses c where c.id = course_id and c.teacher_id = auth.uid())));
create policy enrollments_admin_write on public.enrollments for all to authenticated
using (public.current_user_role() = 'ADMINISTRADOR') with check (public.current_user_role() = 'ADMINISTRADOR');

-- class_sessions
create policy sessions_select on public.class_sessions for select to authenticated
using (public.current_user_role() = 'ADMINISTRADOR'
  or exists (select 1 from public.courses c where c.id = course_id and c.teacher_id = auth.uid())
  or exists (select 1 from public.enrollments e where e.course_id = class_sessions.course_id and e.student_id = auth.uid() and e.status = 'ACTIVA'));
create policy sessions_write on public.class_sessions for all to authenticated
using (public.current_user_role() = 'ADMINISTRADOR' or exists (select 1 from public.courses c where c.id = course_id and c.teacher_id = auth.uid()))
with check (public.current_user_role() = 'ADMINISTRADOR' or exists (select 1 from public.courses c where c.id = course_id and c.teacher_id = auth.uid()));

-- assessments
create policy assessments_select on public.assessments for select to authenticated
using (public.current_user_role() = 'ADMINISTRADOR'
  or exists (select 1 from public.courses c where c.id = course_id and c.teacher_id = auth.uid())
  or exists (select 1 from public.enrollments e where e.course_id = assessments.course_id and e.student_id = auth.uid() and e.status = 'ACTIVA'));
create policy assessments_write on public.assessments for all to authenticated
using (public.current_user_role() = 'ADMINISTRADOR' or exists (select 1 from public.courses c where c.id = course_id and c.teacher_id = auth.uid()))
with check (public.current_user_role() = 'ADMINISTRADOR' or exists (select 1 from public.courses c where c.id = course_id and c.teacher_id = auth.uid()));

-- assessment_scores
create policy scores_select on public.assessment_scores for select to authenticated
using (student_id = auth.uid() or public.current_user_role() = 'ADMINISTRADOR'
  or exists (select 1 from public.assessments a join public.courses c on c.id = a.course_id where a.id = assessment_id and c.teacher_id = auth.uid()));
create policy scores_write on public.assessment_scores for all to authenticated
using (public.current_user_role() = 'ADMINISTRADOR'
  or exists (select 1 from public.assessments a join public.courses c on c.id = a.course_id where a.id = assessment_id and c.teacher_id = auth.uid()))
with check (public.current_user_role() = 'ADMINISTRADOR'
  or exists (select 1 from public.assessments a join public.courses c on c.id = a.course_id where a.id = assessment_id and c.teacher_id = auth.uid()));

-- publicaciones_instagram (MARKETING / ADMINISTRADOR)
create policy publicaciones_all on public.publicaciones_instagram for all to authenticated
using (public.current_user_role() in ('MARKETING','ADMINISTRADOR'))
with check (public.current_user_role() in ('MARKETING','ADMINISTRADOR'));

-- pagos
create policy pagos_select on public.pagos for select to authenticated
using (
  public.current_user_role() = 'ADMINISTRADOR'
  or docente_id = auth.uid()
  or (public.current_user_role() = 'EMPRESA' and empresa_id = public.current_empresa_id())
);
create policy pagos_insert on public.pagos for insert to authenticated
with check (
  public.current_user_role() = 'ADMINISTRADOR'
  or (public.current_user_role() = 'EMPRESA' and pagador_tipo = 'EMPRESA' and empresa_id = public.current_empresa_id())
);
create policy pagos_update on public.pagos for update to authenticated
using (public.current_user_role() = 'ADMINISTRADOR') with check (public.current_user_role() = 'ADMINISTRADOR');
-- Sin policy de DELETE: los pagos no se eliminan, se ANULAN (trazabilidad contable)

-- clases_zoom
create policy clases_zoom_select on public.clases_zoom for select to authenticated
using (
  public.current_user_role() = 'ADMINISTRADOR'
  or docente_id = auth.uid()
  or exists (select 1 from public.enrollments e where e.course_id = clases_zoom.curso_id and e.student_id = auth.uid() and e.status = 'ACTIVA'
             and (e.docente_id is null or e.docente_id = clases_zoom.docente_id))
);
create policy clases_zoom_insert on public.clases_zoom for insert to authenticated
with check (
  public.current_user_role() = 'ADMINISTRADOR'
  or (public.current_user_role() = 'PROFESOR' and docente_id = auth.uid()
      and exists (select 1 from public.cursos_docentes cd where cd.curso_id = clases_zoom.curso_id and cd.docente_id = auth.uid()))
);
create policy clases_zoom_update on public.clases_zoom for update to authenticated
using (public.current_user_role() = 'ADMINISTRADOR' or docente_id = auth.uid())
with check (public.current_user_role() = 'ADMINISTRADOR' or docente_id = auth.uid());

-- La zoom_start_url (enlace de anfitrión) NO debe ser legible por estudiantes:
-- se revoca SELECT de tabla y se concede solo sobre columnas públicas.
revoke select on public.clases_zoom from anon, authenticated;
grant select (id, curso_id, docente_id, titulo, descripcion, zoom_meeting_id, zoom_join_url,
              fecha_inicio, duracion_minutos, estado, simulado, created_at, updated_at)
  on public.clases_zoom to authenticated;

create or replace function public.clase_zoom_start_url(p_clase_id bigint)
returns text language sql stable security definer set search_path = public as $$
  select zoom_start_url from public.clases_zoom
  where id = p_clase_id and (docente_id = auth.uid() or public.current_user_role() = 'ADMINISTRADOR');
$$;
revoke all on function public.clase_zoom_start_url(bigint) from public;
grant execute on function public.clase_zoom_start_url(bigint) to authenticated;

-- eventos_auditoria: lectura solo ADMINISTRADOR; escritura solo vía registrar_evento()
create policy eventos_auditoria_select on public.eventos_auditoria for select to authenticated
using (public.current_user_role() = 'ADMINISTRADOR');

-- ============================================================
-- SUPABASE STORAGE: bucket privado de comprobantes de pago
-- ============================================================
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('comprobantes-pagos', 'comprobantes-pagos', false, 5242880,
        array['application/pdf','image/jpeg','image/png','image/webp'])
on conflict (id) do update set public = false, file_size_limit = 5242880,
  allowed_mime_types = array['application/pdf','image/jpeg','image/png','image/webp'];

drop policy if exists comprobantes_select on storage.objects;
drop policy if exists comprobantes_insert on storage.objects;
-- Ruta esperada: pagos/<pago_id>/<archivo>
create policy comprobantes_select on storage.objects for select to authenticated
using (bucket_id = 'comprobantes-pagos' and (
  public.current_user_role() = 'ADMINISTRADOR'
  or exists (select 1 from public.pagos p
             where p.id::text = (storage.foldername(name))[2]
               and (p.docente_id = auth.uid()
                    or (public.current_user_role() = 'EMPRESA' and p.empresa_id = public.current_empresa_id())))
));
create policy comprobantes_insert on storage.objects for insert to authenticated
with check (bucket_id = 'comprobantes-pagos' and (
  public.current_user_role() = 'ADMINISTRADOR'
  or (public.current_user_role() = 'EMPRESA' and exists (select 1 from public.pagos p
      where p.id::text = (storage.foldername(name))[2] and p.empresa_id = public.current_empresa_id()))
));

-- ============================================================
-- FUNCIÓN: adjuntar comprobante (ADMINISTRADOR o EMPRESA dueña del pago)
-- ============================================================
create or replace function public.adjuntar_comprobante(p_pago_id bigint, p_path text, p_nombre text)
returns void language plpgsql security definer set search_path = public as $$
declare v_pago public.pagos;
begin
  select * into v_pago from public.pagos where id = p_pago_id;
  if not found then raise exception 'Pago no encontrado' using errcode = 'P0002'; end if;
  if public.current_user_role() = 'ADMINISTRADOR'
     or (public.current_user_role() = 'EMPRESA' and v_pago.empresa_id = public.current_empresa_id()) then
    if v_pago.estado = 'ANULADO' then raise exception 'El pago está anulado' using errcode = '22023'; end if;
    update public.pagos set comprobante_path = p_path, comprobante_nombre = p_nombre where id = p_pago_id;
  else
    raise exception 'Sin permisos sobre este pago' using errcode = '42501';
  end if;
end $$;
revoke all on function public.adjuntar_comprobante(bigint,text,text) from public;
grant execute on function public.adjuntar_comprobante(bigint,text,text) to authenticated;

-- ============================================================
-- AUDITORÍA AUTOMÁTICA (atómica, no depende del backend) para pagos y clases Zoom
-- ============================================================
create or replace function public.trg_auditar_pagos()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.eventos_auditoria (tipo_evento, entidad, entidad_id, usuario_id, descripcion, datos)
  values ('PAGO_' || tg_op, 'pagos', new.id::text, auth.uid(),
          'Pago a docente ' || new.docente_id || ' por ' || new.monto || ' ' || new.moneda || ' (' || new.estado || ')',
          jsonb_build_object('docente_id', new.docente_id, 'monto', new.monto, 'moneda', new.moneda,
                             'estado', new.estado, 'metodo_pago', new.metodo_pago,
                             'tiene_comprobante', new.comprobante_path is not null));
  return new;
end $$;
drop trigger if exists pagos_auditoria on public.pagos;
create trigger pagos_auditoria after insert or update on public.pagos
for each row execute function public.trg_auditar_pagos();

create or replace function public.trg_auditar_clases_zoom()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.eventos_auditoria (tipo_evento, entidad, entidad_id, usuario_id, descripcion, datos)
  values ('CLASE_ZOOM_' || tg_op, 'clases_zoom', new.id::text, auth.uid(),
          'Clase "' || new.titulo || '" (' || new.estado || ')',
          jsonb_build_object('curso_id', new.curso_id, 'docente_id', new.docente_id,
                             'fecha_inicio', new.fecha_inicio, 'duracion_minutos', new.duracion_minutos,
                             'estado', new.estado, 'simulado', new.simulado));
  return new;
end $$;
drop trigger if exists clases_zoom_auditoria on public.clases_zoom;
create trigger clases_zoom_auditoria after insert or update on public.clases_zoom
for each row execute function public.trg_auditar_clases_zoom();


-- ============================================================
-- MATRÍCULA AUTOGESTIONADA DEL ESTUDIANTE (APF2)
-- El estudiante NO inserta directo en enrollments (solo ADMIN): lo hace esta función,
-- que valida curso, docente y método, y registra el pago SIMULADO (no se cobra nada).
-- ============================================================
insert into public.permisos (codigo, descripcion)
values ('matriculas:autogestionar', 'El estudiante agrega cursos a su cuenta (con pago simulado)')
on conflict (codigo) do update set descripcion = excluded.descripcion;
insert into public.roles_permisos (rol, permiso) values ('ESTUDIANTE', 'matriculas:autogestionar') on conflict do nothing;

drop policy if exists cursos_docentes_select on public.cursos_docentes;
drop policy if exists cursos_docentes_admin on public.cursos_docentes;
create policy cursos_docentes_select on public.cursos_docentes for select to authenticated using (true);
create policy cursos_docentes_admin on public.cursos_docentes for all to authenticated
using (public.current_user_role() = 'ADMINISTRADOR') with check (public.current_user_role() = 'ADMINISTRADOR');

-- Catálogo: un registro por (curso, docente) con indicador de matrícula vigente
create or replace function public.catalogo_cursos()
returns table(curso_id bigint, nombre text, nivel text, descripcion text, precio numeric,
              docente_id uuid, docente_nombre text, ya_matriculado boolean)
language plpgsql stable security definer set search_path = public as $$
#variable_conflict use_column
begin
  if not public.tiene_permiso('matriculas:autogestionar') then
    raise exception 'Sin permiso matriculas:autogestionar' using errcode = '42501';
  end if;
  return query
  select c.id, c.name, c.level, c.description, c.precio, d.id, d.full_name,
         exists (select 1 from public.enrollments e
                 where e.student_id = auth.uid() and e.course_id = c.id and e.status <> 'RETIRADA')
  from public.courses c
  join public.cursos_docentes cd on cd.curso_id = c.id
  join public.profiles d on d.id = cd.docente_id
  where c.status = 'ACTIVO' and d.status = 'ACTIVO' and d.role = 'PROFESOR'
  order by c.name, d.full_name;
end $$;

-- Matrícula con pago simulado
create or replace function public.matricular_estudiante(p_curso bigint, p_docente uuid, p_metodo text)
returns table(matricula_id bigint, referencia text, monto numeric, curso text)
language plpgsql security definer set search_path = public as $$
#variable_conflict use_column
declare v_precio numeric; v_nombre text; v_ref text; v_id bigint; v_prev public.enrollments;
begin
  if not public.tiene_permiso('matriculas:autogestionar') then
    raise exception 'Sin permiso matriculas:autogestionar' using errcode = '42501';
  end if;
  if upper(coalesce(p_metodo, '')) not in ('TARJETA', 'YAPE', 'PLIN') then
    raise exception 'Método de pago no permitido' using errcode = '22023';
  end if;
  select c.precio, c.name into v_precio, v_nombre from public.courses c where c.id = p_curso and c.status = 'ACTIVO';
  if not found then raise exception 'Curso no disponible' using errcode = '22023'; end if;
  if not exists (select 1 from public.cursos_docentes cd join public.profiles d on d.id = cd.docente_id
                 where cd.curso_id = p_curso and cd.docente_id = p_docente and d.status = 'ACTIVO' and d.role = 'PROFESOR') then
    raise exception 'El docente no dicta este curso' using errcode = '22023';
  end if;

  v_ref := 'SIM-' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 10));
  select * into v_prev from public.enrollments e where e.student_id = auth.uid() and e.course_id = p_curso;
  if found then
    if v_prev.status <> 'RETIRADA' then raise exception 'Ya estás matriculado en este curso' using errcode = '23505'; end if;
    update public.enrollments
       set status = 'ACTIVA', progress = 0, docente_id = p_docente, enrolled_at = now(),
           monto_pagado = v_precio, pago_simulado_ref = v_ref, metodo_pago_simulado = upper(p_metodo)
     where id = v_prev.id returning id into v_id;
  else
    insert into public.enrollments (student_id, course_id, docente_id, progress, status, monto_pagado, pago_simulado_ref, metodo_pago_simulado)
    values (auth.uid(), p_curso, p_docente, 0, 'ACTIVA', v_precio, v_ref, upper(p_metodo))
    returning id into v_id;
  end if;

  insert into public.eventos_auditoria (tipo_evento, entidad, entidad_id, usuario_id, descripcion, datos)
  values ('MATRICULA_AUTOGESTIONADA', 'enrollments', v_id::text, auth.uid(),
          'Matrícula en "' || v_nombre || '" con pago simulado ' || v_ref,
          jsonb_build_object('curso_id', p_curso, 'docente_id', p_docente, 'monto', v_precio,
                             'metodo', upper(p_metodo), 'referencia', v_ref, 'simulado', true));
  return query select v_id, v_ref, v_precio, v_nombre;
end $$;

-- Nombres de los docentes de mis cursos (el estudiante no puede leer profiles de docentes directamente)
create or replace function public.nombres_docentes_matricula()
returns table(id uuid, full_name text)
language sql stable security definer set search_path = public as $$
  select distinct d.id, d.full_name
  from public.enrollments e
  join public.profiles d on d.id = coalesce(e.docente_id, (select c.teacher_id from public.courses c where c.id = e.course_id))
  where e.student_id = auth.uid();
$$;

revoke all on function public.catalogo_cursos() from public;
revoke all on function public.matricular_estudiante(bigint, uuid, text) from public;
revoke all on function public.nombres_docentes_matricula() from public;
grant execute on function public.catalogo_cursos() to authenticated;
grant execute on function public.matricular_estudiante(bigint, uuid, text) to authenticated;
grant execute on function public.nombres_docentes_matricula() to authenticated;

-- Vista con el nombre "matriculas" (alias de enrollments; respeta RLS del usuario que consulta)
create or replace view public.matriculas with (security_invoker = true) as
select id, student_id as estudiante_id, course_id as curso_id, docente_id,
       enrolled_at as fecha_matricula, progress as progreso, status as estado,
       monto_pagado, metodo_pago_simulado, pago_simulado_ref as referencia_pago
from public.enrollments;
grant select on public.matriculas to authenticated;


-- ============================================================
-- REGISTRO PÚBLICO: country en profiles + alta automática de perfil (siempre ESTUDIANTE)
-- El rol NUNCA se toma de los metadatos enviados por el cliente.
-- ============================================================
alter table public.profiles add column if not exists country text;
alter table public.profiles drop constraint if exists profiles_country_check;
alter table public.profiles add constraint profiles_country_check
  check (country is null or country ~ '^[A-Z]{2}$' or country = 'GLOBAL');

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_name text; v_country text;
begin
  v_name := left(coalesce(nullif(btrim(regexp_replace(coalesce(new.raw_user_meta_data->>'full_name', ''), '[<>]', '', 'g')), ''), split_part(new.email, '@', 1)), 100);
  v_country := upper(nullif(btrim(new.raw_user_meta_data->>'country'), ''));
  if v_country is not null and v_country !~ '^[A-Z]{2}$' and v_country <> 'GLOBAL' then v_country := null; end if;
  insert into public.profiles (id, full_name, email, role, status, country)
  values (new.id, v_name, new.email, 'ESTUDIANTE', 'ACTIVO', v_country)
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();
