import React from 'react'
import { Users, BookOpen, Building2, ShieldCheck, ArrowUpRight, Activity } from 'lucide-react'
import DashboardShell from '../components/DashboardShell.jsx'

export default function Administrador({go}){
  return <DashboardShell title="Panel de administración" subtitle="Vista general de la plataforma Lingova" role="Administrador" go={go} admin>
    <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-5">
      {[['Usuarios registrados','142',Users],['Cursos activos','12',BookOpen],['Empresas cliente','8',Building2],['Eventos de auditoría','1,284',ShieldCheck]].map(([t,v,I])=><div key={t} className="bg-white border border-slate-200 rounded-2xl p-6 card-shadow"><div className="w-11 h-11 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center"><I/></div><div className="mt-5 flex items-end justify-between"><div><div className="text-3xl font-black">{v}</div><div className="text-slate-500 mt-1">{t}</div></div><ArrowUpRight className="text-emerald-500"/></div></div>)}
    </div>
    <div className="grid xl:grid-cols-3 gap-6 mt-6">
      <div className="xl:col-span-2 bg-white rounded-2xl border border-slate-200 p-6 card-shadow"><h3 className="font-black text-xl">Resumen de gestión</h3><p className="text-sm text-slate-500 mt-1">Indicadores visuales del sistema</p><div className="mt-8 h-64 flex items-end gap-5 px-3">{[42,58,51,72,64,81,75,90,84,93].map((h,i)=><div key={i} className="flex-1 bg-blue-100 rounded-t-xl relative" style={{height:`${h}%`}}><div className="absolute inset-x-0 bottom-0 bg-blue-600 rounded-t-xl" style={{height:`${Math.max(22,h-25)}%`}}></div></div>)}</div><div className="flex justify-between text-xs text-slate-400 mt-4"><span>Sem 1</span><span>Sem 2</span><span>Sem 3</span><span>Sem 4</span><span>Sem 5</span></div></div>
      <div className="bg-white rounded-2xl border border-slate-200 p-6 card-shadow"><div className="flex items-center gap-3"><div className="w-11 h-11 rounded-xl bg-emerald-50 text-emerald-600 flex items-center justify-center"><Activity/></div><div><h3 className="font-black text-xl">Estado del sistema</h3><p className="text-sm text-slate-500">Resumen visual</p></div></div><div className="mt-6 space-y-4">{[['Plataforma web','Operativa'],['Base de datos','Disponible'],['Auditoría','Activa'],['Módulo académico','Operativo']].map(([a,b])=><div key={a} className="flex justify-between items-center py-3 border-b border-slate-100"><span className="font-semibold text-slate-700">{a}</span><span className="text-xs font-bold px-3 py-1.5 rounded-full bg-emerald-50 text-emerald-600">{b}</span></div>)}</div></div>
    </div>
    <div className="mt-6 bg-white rounded-2xl border border-slate-200 p-6 card-shadow"><h3 className="font-black text-xl">Usuarios recientes</h3><div className="mt-5 overflow-x-auto"><table className="w-full text-left"><thead><tr className="text-xs text-slate-400 border-b"><th className="py-3">Usuario</th><th>Rol</th><th>Curso / Área</th><th>Estado</th></tr></thead><tbody>{[['María López','Estudiante','Business English B1'],['Carlos Vega','Profesor','English A2'],['Lucía Ramos','Estudiante','TOEFL Preparation'],['Diego Torres','Administrador','Gestión general']].map(r=><tr key={r[0]} className="border-b border-slate-100"><td className="py-4 font-bold">{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td><span className="text-xs font-bold bg-blue-50 text-blue-600 rounded-full px-3 py-1.5">Activo</span></td></tr>)}</tbody></table></div></div>
  </DashboardShell>
}
